pyOpenSci/python-package-guide

- .github/workflows/build-book.yml
whyyyyyyyyy??????? 😿 
I get it now. version 5.0  is here... 
see #3
> WHY DON"T YOU LIKE ME HTML PROOFER? 😭 

- .github/workflows/build-book.yml
- _static/pyos.css
- conf.py
- index.md
- requirements.txt
This is a small PR that
* updates to furo them
* fixes spacing in a few places in the css (minor)
* updates the index landing page
Also adds sitemap to create an xml feed to submit to GSC. and open graph
> ADD: Update package theme to furo and add sitemap and opengraph

- _static/pyos.css
- code-style-structure/intro.md
- conf.py
- documentation/hosting-tools/intro.md
- documentation/hosting-tools/website-hosting-optimizing-your-docs.md
- documentation/index.md
- documentation/repository-files/code-of-conduct-file.md
- documentation/repository-files/contributing-file.md
- documentation/repository-files/development-guide.md
- documentation/repository-files/intro.md
- documentation/repository-files/license-files.md
- documentation/repository-files/readme-file-best-practices.md
- documentation/write-user-documentation/create-package-tutorials.md
- documentation/write-user-documentation/document-your-code-api-docstrings.md
- documentation/write-user-documentation/get-started.md
- documentation/write-user-documentation/intro.md
- index.md
- requirements.txt
This pr just moves the entire book over to the pydata sphinx theme. this will allow us additional flexibility as our content expands. no urls are changed with this move. it's simply a theme move and a visual change.
> Fix: move book to pydata_sphinx_theme

- _static/matomo.js
- conf.py
Following 
https://github.com/pydata/pydata-sphinx-theme/pull/1227#issuecomment-1456255520
adding matomo to our guide@
> Add: matomo to guide

- index.md
In light mode, the card titles at https://www.pyopensci.org/python-package-guide/ has dark grey text on a light grey background:
The contrast is good, meeting both of [WCAG's AA and AAA accessibility guidelines](https://webaim.org/standards/wcag/):
However, in dark mode, we get a light grey text on a light grey background, making it hard to read:
It has very low contrast, meeting neither level:
In both cases, we're using Bootstrap's `bg-light` class for the background.
One fix would be to use a darker background in dark mode.
But the cards at https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/web-components.html#cards don't have any special background colour for the panel titles, so shall we follow suit?
If so, we get this:
And:
> A11y: Use PyData Theme's Sphinx Design Components to fix dark mode contrast

- package-structure-code/pyproject-toml-python-package-metadata.md
This is invalid, see https://packaging.python.org/en/latest/tutorials/packaging-projects/ for example.
> fix: incorrect backend key

- package-structure-code/python-package-build-tools.md
This fixes (what I believe to be) two typos.
> fix: typos

- conf.py
Move the the pyOpenSci home page link into the "More" dropdown
> Update conf.py file to reduce the number of items in the top header of our guide - fix for safari.

- package-structure-code/publish-python-package-pypi-conda.md
This is part of the feedback we got from readers. More PRs soon.
> Remove duplicated instructions

- package-structure-code/code-style-linting-format.md
I think we should add basic configurations for flake8 and isort to be compatible with black.
- Isort is easy: `profile = black`
- Flake8 is trickier: rules E203, E501 and W503 need to be excluded
> docs: Add ruff section in code style page

- package-structure-code/python-package-build-tools.md
- package-structure-code/python-package-distribution-files-sdist-wheel.md
Phew - look what one pre-commit pr triggered. more fixes to the docs build - links and alt tags!
> Fix: broken links and add alt tags

- .github/workflows/build-book.yml
to make the latest bot pr happy
> Minor spelling fix

- _static/pyos.css
- conf.py
- index.md
- tests/index.md
This is a minor toctree fix as someone during rebasing i overwrote some things i didn't want to overwrite.
> Fix: fix overwritten card edits

- _static/pyos.css
- index.md
- tests/index.md
One last pass at styles to ensure consistency!
> Fix: more styles fixes

- conf.py
- documentation/index.md
- index.md
- package-structure-code/intro.md
- package-structure-code/pyproject-toml-python-package-metadata.md
- pyproject.toml
- requirements.txt
I went in with the intention of fixing the navigation. However it seems ilke there is a bug in the latest version of pydata_sphinx theme. 
see:
* https://github.com/pydata/pydata-sphinx-theme/issues/1625 where i chimed in on that issue
i am going to see if pinning back to version 15.0 or 14.4 fixes things.
> Fix: a few fixes to support the new theme and also updated cards

- .github/workflows/artifact_redirect.yml
To make the book redirect work you need a secret. This adds that to the build.
> Fix: book redirect build needs secret

- .github/workflows/artifact_redirect.yml
This has a few more fixes to the redirect
> Fix: redirect still has incorrect info

- _static/pyos.css
- conf.py
- tutorials/1-installable-code.md
This is a tiny pr that
* Creates a more reader friendly project name (ends up in the meta tags and social previews)
* Creates the copyright via an f-string so the year is always up to date.
* Grabs the release value from git tags. 
question - will that approach work in ci to get the tags that way? will we need to increase the fetch depth to ensure we already get a tag? Because we don't release often.
> Fix: update project name and make year automated

- .zenodo.json
THis zenodo file should be updated with people who have contributed to the guidebook.
I think we can classify fly-by contributions as 
contributor status
and more in depth reviews as 
author / creator status
@kierisi i'm going to assign this to you here and in asana to help pull together names and orcid's in support of a few new releases in the upcoming weeks and months!! 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206246014367537
- https://app.asana.com/0/0/1206282080041879
> Fix: update zenodo file for new release

- README.md
this also is my testing verified commits!
> Fix: readme file updates

- index.md
I missed adding the navigation link for the enw tutorial on the landing page in the already merged pr. this fixes that!
> Fix: missing link to publish pypi lesson in  current landing page

- package-structure-code/python-package-build-tools.md
- tutorials/1-installable-code.md
- tutorials/get-to-know-hatch.md
- tutorials/intro.md
This is what the intro looks like fully committing to hatch. Setting up that config.toml file for default hatch settings is important as a starting point. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206595156181300
> Fix: use hatch for workflow

- tutorials/add-readme.md
- tutorials/intro.md
This PR adds a new tutorial on creating a readme file. The following tutorials will be:
1. add a license and code of conduct and then
2. add a pyproject.toml file 
The current break in CI relates to the next lesson (links to it) that aren't in this PR but the lesson draft is done. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206433371892147
> Add: readme file tutorial to packaging 101 series

- tutorials/intro.md
This is a tiny fix to the navigation
> Fix: nav for tutorials duplicated

- tutorials/1-installable-code.md
This is a tiny pr that fixes headings in installable module tutorial to be consistent.
> Fix: inconsistent headings

- tutorials/add-readme.md
- hard-wrap the "community" section paragraph for ease of reading
- close the markdown block so the wrap-up paragraph renders normally
> Close markdown block for example README

- index.md
This just addresses 2 minor heading items in recently merged #188 . This can be approved & merged once ci is happy.
> Fix: minor edits

- .github/workflows/build-book.yml
- CONTRIBUTING.md
- conf.py
- noxfile.py
- tutorials/add-license-coc.md
- tutorials/installable-code.md
- tutorials/publish-conda-forge.md
previously, on fix broken stuff: https://github.com/pyOpenSci/python-package-guide/pull/192
on this episode: we add a `docs-test` nox command that fails on errors so we can keep stuff from getting broken <3.
the existing HTML checker is good for something, but it misses stuff like duplicate targets, lexer errors, etc.
> Fix broken stuff 2 (and keep stuff unbroken)

- conf.py
We have updated our governance link so it now lives at handbook/governance. This updates the link to be handbook rather than governance
> Fix: update link to coc

- tutorials/publish-conda-forge.md
Addresses Issue 201 by updating the learning objectives of the publishing to conda-forge tutorial in `tutorials/publish-conda-forge.md`
> Fix: Issue 201 - conda-forge tutorial learning objectives

- tutorials/get-to-know-hatch.md
> update: hatch tutorial

- tutorials/publish-conda-forge.md
Tiny typo: "it" should be "is".
> Update publish-conda-forge.md to fix tiny typo

- tutorials/publish-pypi.md
Remove older version of "next lesson" line.
> Update publish-pypi.md to remove near-duplicate line.

- tutorials/intro.md
Remove duplicative Learn how to publish your package to PyPI in this tutorial
> Update intro.md: Remove Duplicate Link/Sentence

- package-structure-code/python-package-build-tools.md
Support for building using other backends happened toward the end of 2023
> Update text to reflect modern Hatch

- tutorials/add-license-coc.md
Use uppercase and fixed-pitch when references to license and code of conduct are more likely references to actual files.  (No formatting added in alt text.)  Also tweak a few grammatical issues.
> More consistent LICENSE and CODE_OF_CONDUCT usage

- tutorials/publish-pypi.md
Refer to "test PyPI" with consistent case and punctuation (with the exception of uppercase T when this appears at the start of a sentence).
> Update publish-pypi.md with consistent usage for "test PyPI".

- tutorials/installable-code.md
When users remove python versions from the classifiers table, they should update the requires-python language to reflect the python versions supported.
> Include missed update step pyproject.toml

- conf.py
- documentation/repository-files/readme-file-best-practices.md
- tutorials/get-to-know-hatch.md
This should fix the warnings being raised by sphinx build
> Fix: sphinx warnings

- CONTRIBUTING.md
- examples/pure-hatch/pyproject.toml
- examples/pure-setuptools/pyproject.toml
- package-structure-code/pyproject-toml-python-package-metadata.md
This is my proof-of-concept of replacing most code blocks with linteralincludes from separate files maintained in the VCS. It is not meant to be merged as-is but to inspire discussion with a live example.
The idea is that, rather than type out example code every time, code that is often nearly or entirely identical, this code can be written out once and reused across the documentation. 
Pros:
* examples can't get out of sync
* readers see the same example code everywhere, maintaining consistency
* the example files can be fully linted/tested as part of an overall working project structure
Unintentionally, just moving this file's examples to individual files revealed two syntax errors at pyproject-toml-python-package-metadata.md:{200,209}.
Cons:
* an extra layer of abstraction, possible …
> literalinclude directives

- tutorials/installable-code.md
Represent version in a consistent way for issue #257
> update version from 0.1.0 to 0.1

- tutorials/publish-pypi.md
- tutorials/pyproject-toml.md
Updated _most_ remaining references to version from three number to two number versions:
- `0.1.0` -> `0.1`
- `0.1.1` -> `0.2`
I did not touch the following. Let me know if that is desired:
1) References to version in example shell output because I'm not 100% sure if that would change; I suspect it would , but would like to confirm. e.g. `dist/pyospackage-0.1.0.tar.gz` etc. in `publish-pypi.md`
2) Reference inside an image alt text, where I suspect the alt text should correctly describe the image (also in `publish-pypi.md`)
3) References outside of `tutorials/`
(Continuation of #257)
> Update version references in tutorial: 0.1.0 -> 0.1

- tutorials/get-to-know-hatch.md
> Add command line example for finding hatch config file location

- tutorials/intro.md
It was slightly confusing to have 'Migrate setup.py to a pyproject.toml' (for existing packages) in the getting started/ tutorial setup portion of the table of contents/ nav. Proposing to move it down under a new heading 'Hatch for Existing Packages'
Thank you!
> Fixing Table of Contents/ Nav

- documentation/repository-files/readme-file-best-practices.md
- package-structure-code/publish-python-package-pypi-conda.md
- package-structure-code/python-package-structure.md
- tutorials/publish-conda-forge.md
The site that hosts community-built packages/channels (e.g., conda-forge & bioconda) packages is officially called "anaconda.org", not "Anaconda Cloud".  (The latter is a different Anaconda Inc product.)
> Replace usage of "Anaconda Cloud" in various contexts

- .github/workflows/build-book.yml
This PR fixes #237 and includes actions version updates for:
- upload-artifact
- cache
- setup-python
- checkout
They were done as separate commits and should be easy to pickoff if not all of them are needed or wanted.
> Update github actions versions to current

- package-structure-code/python-package-distribution-files-sdist-wheel.md
> Change formatting to satisfy codespell check

- README.md
- package-structure-code/code-style-linting-format.md
- package-structure-code/declare-dependencies.md
- package-structure-code/pyproject-toml-python-package-metadata.md
- package-structure-code/python-package-build-tools.md
- tutorials/add-readme.md
- tutorials/installable-code.md
- tutorials/publish-conda-forge.md
- tutorials/publish-pypi.md
I noticed some inconsistencies around how `pip` is invoked in the package guide, so I've gone through and made sure all pip commands are invoked with `python -m pip ...` as recommended in the guide here:
https://www.pyopensci.org/python-package-guide/package-structure-code/declare-dependencies.html#install-dependency-groups
> Always use `python -m` with pip

- tutorials/add-license-coc.md
I was creating a `CODE_OF_CONDUCT` following the guidelines and noticed that there is no mention of needing to fill in any placeholder information, so I added a sentence as a heads-up. (Currently, the placeholder is `[INSERT CONTACT METHOD]`, but that may change.
> Mention that the code of conduct has placeholder values

- .gitignore
- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
This PR **adds support for internationalization** to the Package Guide as described in issue  #287.
See the translation guide in PR #304 for a description of the workflow.
- Documented and cleaned up the current nox sessions in `noxfile.py` to make it easier to maintain as the configuration becomes more complex
- Parameterized the nox configuration options as variables at the top of the file
- Added new sessions to Nox:
- `update-translations`: create and update translations files for the languages defined in `LANGUAGES`
- `build-translations`: build the guide in the languages defined in `LANGUAGES`
- `docs-live-lang`: a convenience session to launch docs-live using a specific language build
- `build-translations-test`: a convenience session to run docs-test using a specific language …
> Add support for internationalization to the guide

- TRANSLATING.md
This PR **adds a translation guide** to the Package Guide to help contributors get started contributing to the translation process.
The nox sessions described in the guide in this PR are defined in PR #298 (Add support for internationalization to the guide)
I wrote a first draft of a Translation Guide (TRANSLATING.md) similar to the CONTRIBUTING.md guide to help new contributors understand the Translation workflow and get started with the process.
It assumes the reader is on the beginner end of the technical spectrum (translation is a good opportunity for people new to open source) and does not necessarily know internationalization and localization, so it is a little on the verbose side.
This guide will also help the pyOpenSci community involved in the guide understand the changes …
> Add a translation guide for contributors

- .pre-commit-config.yaml
- locales/es/LC_MESSAGES/index.po
- locales/es/LC_MESSAGES/tests.po
This PR adds the beginning of the Spanish translation, it is related to #298 and #304.
- Translated the guide homepage (index.md) into Spanish
- Translated the Tests section into Spanish
Build the Spanish translation using this command:
```
nox -s docs-live -- -D language=es
```
Browse to ``http://localhost:8000`` to browse it.
Note: Once PR #298 is merged, it will add the new nox sessions and building a translation will be easier:
```
nox -s docs-live-lang -- es
```
> Start spanish translation

- CONTRIBUTING.md
This PR prepares the CONTRIBUTING guide for the SciPy development sprints. See this issue #310.
I added an initial structure with placeholders to breakdown the task of updating the document into smaller tasks that can be tackled by beginner contributors during the sprint.
The issue [Update the Contributors Guide](https://github.com/pyOpenSci/python-package-guide/issues/310) can be used to coordinate the work, new contributors can choose parts of the file to work on while making sure that work is not duplicated.
> Structure the CONTRIBUTING guide to define sprint tasks

- documentation/repository-files/readme-file-best-practices.md
- locales/es/LC_MESSAGES/documentation.po
- tutorials/add-readme.md
part of: https://github.com/pyOpenSci/software-peer-review/issues/293
> update badges url

- tutorials/get-to-know-hatch.md
Added links to hatch installation documentation for pip and conda. Also, moved the tip up into the installation section of [tutorials/get-to-know-hatch.html](https://www.pyopensci.org/python-package-guide/tutorials/get-to-know-hatch.html). 
Addresses issue #319
> Added links for installing hatch via pip and conda.

- package-structure-code/python-package-distribution-files-sdist-wheel.md
- tutorials/installable-code.md
- tutorials/pyproject-toml.md
The use of Unicode should be avoided unless necessary.
> docs: fix the Unicode apostrophe issue in markdown files

- documentation/hosting-tools/myst-markdown-rst-doc-syntax.md
"vanilla of": It is not an easy expression for non-English native speakers to understand. I removed this phrase because it makes enough sense without it.
> docs: drop "vanilla of" from sentence

- .all-contributorsrc
It is better to show contributors name alphabetically.
- [Bot Configuration](https://allcontributors.org/docs/en/bot/configuration)
> docs: set Bot configuration `contributorsSortAlphabetically` True

- locales/es/LC_MESSAGES/documentation.po
Fix missing double quote in Spanish version of documentation.po file.
> Fix format of Spanish documentation.po file

- package-structure-code/publish-python-package-pypi-conda.md
Looks like this sentence should say "channel" instead of "package" in the section about conda and pip.
> docs: fix wrong word in section about conda repositories

- package-structure-code/intro.md
Rephrase two sentences to avoid confusion with the use of the word tool: tool as the software that will be in the package and tool as the packaging tool that will be used to make the package.
> docs: Small clarification to avoid confusion

- documentation/repository-files/intro.md
- index.md
- tutorials/publish-pypi.md
Fix typo in documentation from Github to GitHub.
> docs: fix typo in documentation from Github to GitHub

- package-structure-code/publish-python-package-pypi-conda.md
Use canonical links for bioconda and conda-forge to avoid htmlproofer timeouts
> Update links in publish-python-package-pypi-conda.md

- noxfile.py
Fixes #419 
Removes the option to reuse the virtual environments for nox sessions from noxfile.py
> Remove option to reuse virtual-env for nox sessions

- package-structure-code/pyproject-toml-python-package-metadata.md
docs: Fix small typo from LIcense to License.
> docs: Fix small typo from LIcense to License

- package-structure-code/intro.md
- package-structure-code/python-package-distribution-files-sdist-wheel.md
- package-structure-code/python-package-structure.md
- tests/index.md
- tutorials/intro.md
This is the start of a set of small pr's that cross link to other content in our guidebook. This is also a good opportunity for us to identify things that we might want to add, change, or enhance. 
Finally, I noticed that our language was a bit too "gentle" and suggestive vs being definitive. I think we can be definite and confident now that we've been taught this stuff numerous times!
> [dec 12 merge] fix: add cross links to the packaging guide

- documentation/repository-files/code-of-conduct-file.md
- documentation/repository-files/contributing-file.md
- documentation/repository-files/development-guide.md
- documentation/repository-files/license-files.md
- documentation/repository-files/readme-file-best-practices.md
- package-structure-code/pyproject-toml-python-package-metadata.md
This PR makes the contributing file more engaging and descriptive. it highlights this file as being a "Welcome mat" of sorts that invites contributors in and guides them through the process. 
Let's try to merge this by Feb 3!! All feedback is welcome!
> feat(contrib file): update to contributing and links to other resources

- tutorials/publish-conda-forge.md
> Fix type form "that ou create" to "that you create"

- index.md
- tutorials/intro.md
Just a very minor update to make the toctree more clear
> feat: Update links to say create a package

- conf.py
- noxfile.py
Fix: #476 
simple enough - just passing the production env to the language building step.
<details>
<summary>edit: no longer true</summary>
changes the production baseurl to be the absolute path rather than the full URL - should be same behavior when deployed, but when testing locally it otherwise would have sent you to the live site rather than the local version.
since this session is intended for deployment, and in deployment we are under the `python-package-guide/` path, when previewing this you would need to move the build output from `_build/html` to `_build/html/python-package-guide` (if you are e.g. launching `http-server` from `_build/html`). this shoudln't be a problem in practice since you shouldn't need to directly preview the production build all that often, and the …
> fix: pass env to language session

- .github/workflows/build-book.yml
I think we should be catching 404s but ignoring timeout errors in CI. let's see if that helps
> Fix: catch 404s but ignore time out errors

- .circleci/config.yml
- .github/workflows/build-book.yml
Testing https://github.com/pyOpenSci/python-package-guide/pull/483#issuecomment-2870401994
> fix: use python 3.13 in ci actions

- TRANSLATING.md
- bibliography.bib
- documentation/repository-files/intro.md
- documentation/repository-files/license-files.md
- package-structure-code/code-style-linting-format.md
Just fixing a few bad links :)
> fix: bad links

- _static/pyos.css
This fixes the table on tools to be more readable in light mode
> fix: styles in light mode in tables are white

- tutorials/publish-conda-forge.md
I had issues a while back publishing a package to conda forge with the distribution named `data-morph-ai`. It turned out that the PyPI source URL needed to be
```
https://pypi.org/packages/source/d/data-morph-ai/data_morph_ai-{{ version }}.tar.gz
```
instead of 
```
https://pypi.org/packages/source/d/data-morph-ai/data-morph-ai-{{ version }}.tar.gz
```
> PyPI source URL for conda recipes needs to use underscores instead of hyphens

- .circleci/config.yml
- .github/workflows/build-book.yml
- _ext/rss.py
- tutorials/add-license-coc.md
- tutorials/add-readme.md
- tutorials/command-line-reference.md
- tutorials/get-to-know-hatch.md
- tutorials/installable-code.md
- tutorials/intro.md
- tutorials/publish-conda-forge.md
- tutorials/publish-pypi.md
- tutorials/pyproject-toml.md
- tutorials/setup-py-to-pyproject-toml.md
Fixes: #507 
Taking the idea from @stefmolin , here we get the `pubDate` from the mtime of the file. In CI we restore those from the commit history.
There is a minor bit of semantic mismatch between the RSS feed/RSS spec and what we might want for the site - the RSS field is `pubDate`, or the date that the item was *published.* I don't think the spec is prescriptive about what that means, e.g. updating a file could be re-publishing it (that's how we treat it here). Usually it's good to treat the original publication date and the update date separately when displaying: e.g. "Originally published: 2020-01-01, updated: 2025-06-04" since both of those are independently meaningful for a reader. Currently we don't display the date on the site, but i renamed the parameter to `date_updated` in …
> Get RSS `pubDate` from mtimes

- noxfile.py
Fixes: https://github.com/pyOpenSci/python-package-guide/issues/523
previously the `_build` directory was not being correctly ignored by sphinx-autobuild because the glob `*`'s being added to the front and back of the ignored directory aren't compatible with how sphinx-autobuild does filtration. this prevents infinite builds and correctly ignores the whole `_build` directory.
> correctly ignore `_build` directory

- locales/ja/LC_MESSAGES/TRANSLATING.po
- locales/ja/LC_MESSAGES/documentation.po
- locales/ja/LC_MESSAGES/index.po
- locales/ja/LC_MESSAGES/package-structure-code.po
- locales/ja/LC_MESSAGES/tutorials.po
Updated the Japanese translation files using `nox -s update-language -- ja` to make sure they are up to date with the current English version in preparation for the SciPy sprints.
> Update Japanese translation files

- tutorials/publish-pypi.md
The `publish-pypi.md` file ends with the start of code block (https://github.com/pyOpenSci/python-package-guide/blob/01de29ee6f6a08f4d1bd433ad6ea1824788c1396/tutorials/publish-pypi.md?plain=1#L403) and this causes issues when rendering the page, as per the attached screenshot:
This is a tiny fix while working on the trusted publishing tutorial (#253).
> Remove stray characters at end of tutorial

- _ext/translation_graph.py
- _static/pyos.css
related to: https://github.com/pyOpenSci/python-package-guide/pull/539
fixes: https://github.com/pyOpenSci/python-package-guide/issues/532
sorry i couldn't help with this during the sprint - i puzzled over this for quite awhile in the initial implementation, i was just afk during those hours.
the basic problem is that plotly has a pretty messy way of handling styles. there isn't *really* a uniform way of passing style information through a complex plot object, and in particular it seems to accept full css expressions in some places, plotly-specific values other places - and probably most confusing, an undocumented subset of css in a third set of places.
font color seems to be one of those third places, where if you pass an `rgb(x,y,z)` string there, it works, but everything else is …
> colors for hovertext in light and dark mode

- index.md
See "✨ Code style & Format ✨" here: https://www.pyopensci.org/python-package-guide/#contributing
> Fix link to code style (it was pointing to CONTRIBUTING)

- CONTRIBUTING.md
- conf.py
- documentation/hosting-tools/publish-documentation-online.md
- documentation/hosting-tools/website-hosting-optimizing-your-docs.md
- documentation/repository-files/license-files.md
- documentation/repository-files/readme-file-best-practices.md
- locales/es/LC_MESSAGES/documentation.po
- locales/ja/LC_MESSAGES/documentation.po
- package-structure-code/python-package-build-tools.md
- package-structure-code/python-package-distribution-files-sdist-wheel.md
- tests/code-cov.md
- tests/run-tests.md
- tests/write-tests.md
- tutorials/get-to-know-hatch.md
- tutorials/intro.md
Follow-up to #551
Proposes updating all the links that are responding with `301 - Moved Permanently`. These links are mostly "working" for users of the documentation, but by redirecting. This proposes just directly linking to the final destinations.
* faster page loads
* reduced risk of sending users to broken pages or those taken over by totally unrelated content (in the event that redirects are removed and/or domain registration expires)
Ran the following from the root of the repo.
```shell
nox -e docs-linkcheck
```
This PR fixes the following:
<details><summary>17 permanent redirects (click me)</summary>
```text
tests/code-cov.md:31: [redirected permanently] https://codecov.io/ to https://about.codecov.io/
tests/run-tests.md:80: [redirected permanently] https://codecov.io/ to …
```
> docs: fix links that redirect permanently
