pyOpenSci/python-package-guide

documentation/index.md
index.md
package-structure-code/intro.md

This fixes the mess in the image below 😆 yikes how did i miss that in my local builds?

Fix: broken navigation

---

documentation/repository-files/code-of-conduct-file.md
documentation/repository-files/license-files.md
package-structure-code/pyproject-toml-python-package-metadata.md
package-structure-code/python-package-distribution-files-sdist-wheel.md

This is a pr to merge all of copy edits i've made while creating the lessons. there are a few broken links that i'll need to pull (links to tutorials).
i'm trying to make the current pr's smaller and more scoped to faciliate easier review (thank you @willingc for that suggestion)

Fix: cleanup of existing pages as we create tutorials

---

.all-contributorsrc

Fix: invalid json in contribs file

---

conf.py

this is the start of fixing the sitemap

Fix: sitemap baseurl

---

conf.py

This should fix the seo issues we're having!!

Fix: sitemap url is wrong

---

index.md

This is a last fix to update the landing page nav.

Fix: update homepage nav

---

package-structure-code/publish-python-package-pypi-conda.md

These lines were added in #177. I chose the grammar that I prefer (+1 to commas).

Fix typo of duplicate lines

---

.zenodo.json

added Eli Schwartz, Ivan Ogasawara, jaimergp, h-vetinari, Tom Russell, and Jackson Burns as contributors.

UPDATE: added new contributors

---

.zenodo.json

Added Carol Willing to contributors!

UPDATE: added Carol to contributors

---

.zenodo.json

Removed duplicate entries for:
* Carol Willing 
* Eli Schwartz

FIX: removed duplicates

---

noxfile.py

Oop fixing docs tests after requirements gone away :)

all my requirements gone

---

.github/workflows/main.yml

This will add any issue labeled sprintable or help-wanted to our project board!

Add: help wanted automated workflow to guidebook repo

---

locales/es/LC_MESSAGES/CONTRIBUTING.po
locales/es/LC_MESSAGES/TRANSLATING.po
locales/es/LC_MESSAGES/documentation.po
locales/es/LC_MESSAGES/package-structure-code.po
locales/es/LC_MESSAGES/tutorials.po

This PR just creates the additional translation files that someone in the SciPy development sprints would need if they want to contribute directly from GitHub.
I also created an issue to help coordinate the work #313

Prepare translation files for SciPy sprint

---

CONTRIBUTING.md

Updated the [Contributing guide](https://github.com/pyOpenSci/python-package-guide/blob/main/CONTRIBUTING.md) with text on how to fork a repo. 
Contributes to issue #310

Updated Contributions.md with text on forking repos

---

README.md

ref https://allcontributors.org/docs/en/bot/faq

docs: update all-contributors badge to new version

---

documentation/hosting-tools/website-hosting-optimizing-your-docs.md

Update a link that change to include the new anchor used on the target site.
This fixes the CI error in some of the recent PRs

Update a link in website-hosting-optimizing-your-docs.md with correct anchor

---

.zenodo.json

To support a new release of the packaging guide, let's make sure that we have all new contributors represented in our zenodo file

feat: Update contributors to the packaging giudebook

---

.zenodo.json

As title says - adding myself to contributors guide after supporting the translation of the packaging guide to Spanish. Thanks @lwasser for the heads up!

feat: adding @RobPasMue to contributors list

---

.zenodo.json

Add `Tetsuo Koyama` to zenodo file.

docs: add `Tetsuo Koyama` to zenodo file

---

TRANSLATING.md

Fix link of PyOpenSci Discord server

---

.github/workflows/crowdin_sync.yml
crowdin.yml

A draft attempt at connecting crowdin with github

feat: crowdin.yml file

---

.github/workflows/build-book.yml

Small fix - working with @flpm at pycon us :)

Fix: ignore status code 200

---

noxfile.py
tutorials/create-python-package.md
tutorials/develop-python-package-hatch.md
tutorials/intro.md

This is a new lesson that i've been working on while developing our workshop. minus well add it here!

feat: new lesson on hatch envs
